git:
  depth: 1

language: c

matrix:

  include:

    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - PKGI_CC=gcc-7

    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - PKGI_CC=clang-5.0

    - os: osx
      osx_image: xcode9.1
      env:
        - PKGI_CC=clang

script:
  - CC=${PKGI_CC} make
